API1_KEY = "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"
API_BASE = "https://api.groq.com/openai/v1"
SECRET_KEY = "GDG-WINNER-2025"
API2_KEY = "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"
